version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    env_file:
      - .env
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    restart: always
    env_file:
      - .env
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge